
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui
{
	public partial class PlayerBin
	{
		private global::Gtk.HBox mainbox;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox videobox;

		private global::Gtk.HBox controlsbox;

		private global::Gtk.HBox buttonsbox;

		private global::Gtk.Button closebutton;

		private global::Gtk.Button drawbutton;

		private global::Gtk.Button playbutton;

		private global::Gtk.Button pausebutton;

		private global::Gtk.Button prevbutton;

		private global::Gtk.Button nextbutton;

		private global::Gtk.Label tlabel;

		private global::Gtk.HScale timescale;

		private global::Gtk.Label timelabel;

		private global::Gtk.Button volumebutton;

		private global::Gtk.VBox vbox3;

		private global::Gtk.VScale vscale1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.PlayerBin
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.PlayerBin";
			// Container child LongoMatch.Gui.PlayerBin.Gtk.Container+ContainerChild
			this.mainbox = new global::Gtk.HBox ();
			this.mainbox.Name = "mainbox";
			this.mainbox.Spacing = 6;
			// Container child mainbox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.videobox = new global::Gtk.HBox ();
			this.videobox.Name = "videobox";
			this.videobox.Spacing = 6;
			this.vbox2.Add (this.videobox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.videobox]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.controlsbox = new global::Gtk.HBox ();
			this.controlsbox.Name = "controlsbox";
			this.controlsbox.Spacing = 6;
			// Container child controlsbox.Gtk.Box+BoxChild
			this.buttonsbox = new global::Gtk.HBox ();
			this.buttonsbox.Name = "buttonsbox";
			this.buttonsbox.Homogeneous = true;
			// Container child buttonsbox.Gtk.Box+BoxChild
			this.closebutton = new global::Gtk.Button ();
			this.closebutton.Name = "closebutton";
			this.closebutton.UseUnderline = true;
			// Container child closebutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Dnd);
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w3.Add (w6);
			w2.Add (w3);
			this.closebutton.Add (w2);
			this.buttonsbox.Add (this.closebutton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.buttonsbox[this.closebutton]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child buttonsbox.Gtk.Box+BoxChild
			this.drawbutton = new global::Gtk.Button ();
			this.drawbutton.Name = "drawbutton";
			this.drawbutton.UseUnderline = true;
			// Container child drawbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-select-color", global::Gtk.IconSize.Menu);
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w12.Add (w15);
			w11.Add (w12);
			this.drawbutton.Add (w11);
			this.buttonsbox.Add (this.drawbutton);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.buttonsbox[this.drawbutton]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child buttonsbox.Gtk.Box+BoxChild
			this.playbutton = new global::Gtk.Button ();
			this.playbutton.Name = "playbutton";
			this.playbutton.UseUnderline = true;
			this.playbutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child playbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w20 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w21 = new global::Gtk.HBox ();
			w21.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Button);
			w21.Add (w22);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w24 = new global::Gtk.Label ();
			w21.Add (w24);
			w20.Add (w21);
			this.playbutton.Add (w20);
			this.buttonsbox.Add (this.playbutton);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.buttonsbox[this.playbutton]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			// Container child buttonsbox.Gtk.Box+BoxChild
			this.pausebutton = new global::Gtk.Button ();
			this.pausebutton.Name = "pausebutton";
			this.pausebutton.UseUnderline = true;
			this.pausebutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child pausebutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w30 = new global::Gtk.HBox ();
			w30.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-pause", global::Gtk.IconSize.Button);
			w30.Add (w31);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w33 = new global::Gtk.Label ();
			w30.Add (w33);
			w29.Add (w30);
			this.pausebutton.Add (w29);
			this.buttonsbox.Add (this.pausebutton);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.buttonsbox[this.pausebutton]));
			w37.Position = 3;
			w37.Expand = false;
			w37.Fill = false;
			// Container child buttonsbox.Gtk.Box+BoxChild
			this.prevbutton = new global::Gtk.Button ();
			this.prevbutton.Name = "prevbutton";
			this.prevbutton.UseUnderline = true;
			this.prevbutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child prevbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w38 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w39 = new global::Gtk.HBox ();
			w39.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w40 = new global::Gtk.Image ();
			w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-previous", global::Gtk.IconSize.Button);
			w39.Add (w40);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w42 = new global::Gtk.Label ();
			w39.Add (w42);
			w38.Add (w39);
			this.prevbutton.Add (w38);
			this.buttonsbox.Add (this.prevbutton);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.buttonsbox[this.prevbutton]));
			w46.Position = 4;
			w46.Expand = false;
			w46.Fill = false;
			// Container child buttonsbox.Gtk.Box+BoxChild
			this.nextbutton = new global::Gtk.Button ();
			this.nextbutton.Sensitive = false;
			this.nextbutton.Name = "nextbutton";
			this.nextbutton.UseUnderline = true;
			this.nextbutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child nextbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w47 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w48 = new global::Gtk.HBox ();
			w48.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w49 = new global::Gtk.Image ();
			w49.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-next", global::Gtk.IconSize.Button);
			w48.Add (w49);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w51 = new global::Gtk.Label ();
			w48.Add (w51);
			w47.Add (w48);
			this.nextbutton.Add (w47);
			this.buttonsbox.Add (this.nextbutton);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.buttonsbox[this.nextbutton]));
			w55.Position = 5;
			w55.Expand = false;
			w55.Fill = false;
			this.controlsbox.Add (this.buttonsbox);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.controlsbox[this.buttonsbox]));
			w56.Position = 0;
			w56.Expand = false;
			w56.Fill = false;
			// Container child controlsbox.Gtk.Box+BoxChild
			this.tlabel = new global::Gtk.Label ();
			this.tlabel.Name = "tlabel";
			this.tlabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Time:");
			this.controlsbox.Add (this.tlabel);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.controlsbox[this.tlabel]));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			// Container child controlsbox.Gtk.Box+BoxChild
			this.timescale = new global::Gtk.HScale (null);
			this.timescale.Name = "timescale";
			this.timescale.UpdatePolicy = ((global::Gtk.UpdateType)(1));
			this.timescale.Adjustment.Upper = 1;
			this.timescale.Adjustment.PageIncrement = 1;
			this.timescale.Adjustment.StepIncrement = 1;
			this.timescale.Adjustment.Value = 1;
			this.timescale.DrawValue = false;
			this.timescale.Digits = 0;
			this.timescale.ValuePos = ((global::Gtk.PositionType)(2));
			this.controlsbox.Add (this.timescale);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.controlsbox[this.timescale]));
			w58.Position = 2;
			// Container child controlsbox.Gtk.Box+BoxChild
			this.timelabel = new global::Gtk.Label ();
			this.timelabel.Name = "timelabel";
			this.controlsbox.Add (this.timelabel);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.controlsbox[this.timelabel]));
			w59.Position = 3;
			w59.Expand = false;
			// Container child controlsbox.Gtk.Box+BoxChild
			this.volumebutton = new global::Gtk.Button ();
			this.volumebutton.Name = "volumebutton";
			this.volumebutton.UseUnderline = true;
			this.volumebutton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child volumebutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w60 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w61 = new global::Gtk.HBox ();
			w61.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w62 = new global::Gtk.Image ();
			w62.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_volume", global::Gtk.IconSize.Button);
			w61.Add (w62);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w64 = new global::Gtk.Label ();
			w61.Add (w64);
			w60.Add (w61);
			this.volumebutton.Add (w60);
			this.controlsbox.Add (this.volumebutton);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.controlsbox[this.volumebutton]));
			w68.Position = 4;
			w68.Expand = false;
			w68.Fill = false;
			this.vbox2.Add (this.controlsbox);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.controlsbox]));
			w69.Position = 1;
			w69.Expand = false;
			this.mainbox.Add (this.vbox2);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.mainbox[this.vbox2]));
			w70.Position = 0;
			// Container child mainbox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vscale1 = new global::Gtk.VScale (null);
			this.vscale1.WidthRequest = 45;
			this.vscale1.Sensitive = false;
			this.vscale1.Name = "vscale1";
			this.vscale1.UpdatePolicy = ((global::Gtk.UpdateType)(1));
			this.vscale1.Inverted = true;
			this.vscale1.Adjustment.Lower = 1;
			this.vscale1.Adjustment.Upper = 28;
			this.vscale1.Adjustment.PageIncrement = 3;
			this.vscale1.Adjustment.PageSize = 1;
			this.vscale1.Adjustment.StepIncrement = 1;
			this.vscale1.Adjustment.Value = 25;
			this.vscale1.DrawValue = true;
			this.vscale1.Digits = 0;
			this.vscale1.ValuePos = ((global::Gtk.PositionType)(3));
			this.vbox3.Add (this.vscale1);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vscale1]));
			w71.Position = 0;
			this.mainbox.Add (this.vbox3);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.mainbox[this.vbox3]));
			w72.Position = 1;
			w72.Expand = false;
			w72.Fill = false;
			this.Add (this.mainbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.closebutton.Hide ();
			this.prevbutton.Hide ();
			this.nextbutton.Hide ();
			this.controlsbox.Hide ();
			this.Show ();
			this.closebutton.Clicked += new global::System.EventHandler (this.OnClosebuttonClicked);
			this.drawbutton.Clicked += new global::System.EventHandler (this.OnDrawButtonClicked);
			this.playbutton.Clicked += new global::System.EventHandler (this.OnPlaybuttonClicked);
			this.pausebutton.Clicked += new global::System.EventHandler (this.OnPausebuttonClicked);
			this.prevbutton.Clicked += new global::System.EventHandler (this.OnPrevbuttonClicked);
			this.nextbutton.Clicked += new global::System.EventHandler (this.OnNextbuttonClicked);
			this.timescale.ValueChanged += new global::System.EventHandler (this.OnTimescaleValueChanged);
			this.timescale.AdjustBounds += new global::Gtk.AdjustBoundsHandler (this.OnTimescaleAdjustBounds);
			this.volumebutton.Clicked += new global::System.EventHandler (this.OnVolumebuttonClicked);
			this.vscale1.FormatValue += new global::Gtk.FormatValueHandler (this.OnVscale1FormatValue);
			this.vscale1.ValueChanged += new global::System.EventHandler (this.OnVscale1ValueChanged);
		}
	}
}
