/*
  #
  #  This file is part of ChronoJump
  #
  #  ChronoJump is free software; you can redistribute it and/or modify
  #   it under the terms of the GNU General Public License as published by
  #    the Free Software Foundation; either version 2 of the License, or
  #     (at your option) any later version.
  #
  #  ChronoJump is distributed in the hope that it will be useful,
  #   but WITHOUT ANY WARRANTY; without even the implied warranty of
  #    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  #     GNU General Public License for more details.
  #
  #  You should have received a copy of the GNU General Public License
  #   along with this program; if not, write to the Free Software
  #    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
  #
  #   Copyright (C) 2017     Xavier Padullés <x.padulles@gmail.com>
  #   Copyright (C) 2017     Xavier de Blas <xaviblas@gmail.com>

V0.1
  Initial version
V0.2
  data is int instead of float (to easy C# binary read). Force is multiplied by 100.
  Added start_capture_binary & start_capture_text for testing purposes. Note start_capture is binary.
  changedZ is sent by serial port (not yet to ble) as sensor_t.incEncoderZ

--------------
When encoder pulses reach PPS (PulsesPerSample) the time is acquired
Every 6250 us (160 Hz) the force is measured
*/

#include <Preferences.h>  // Used to store tare and calibration in the flash
#include <elapsedMillis.h>
#include <HX711.h>

//Version number. It always need to start with: "Force_Sensor-"
String version = "EncoderForce-0.2";

bool commandFlag = false;

enum sensor_t {
  none = 0,
  rca = 1,
  loadCell = 2,
  incEncoder = 3,
  incEncoderZ = 4,
};

// que passa si el fallo és que alguna part de lal estructura s'actualitza en aquell moment i és null?
struct sample_t {
  sensor_t sensorType;
  unsigned int time;
  //float data;
  int data;
};

sample_t sample;

// ---- testing stuff ---->
struct testing_t {
  int ta = 151653132; //9*256^3 + 10*256^2 + 11*256^1 +12
  int tb = 84281096; //5*256^3 + 6*256^2 + 7*256^1 +8
  int tc = 16909060; //1*256^3 + 2*256^2 + 3*256^1 +4
};

testing_t testingData;
bool testing_b = false;
// <---- testing stuff ----


//whether the tranmission is in binary format or not
enum format_t {
  binary = 0,
  text = 1,
};

format_t transmissionFormat = binary; //default
//format_t transmissionFormat = text;


// Preparing the flash storage for tare and calibration.
Preferences preferences;

//Whether the sensor has to capture or not
boolean capturing = false;

elapsedMicros totalTime = 0;

const int rcaPin = 3;

unsigned long triggerTime = 0;
bool rcaState = digitalRead(rcaPin);
bool lastRcaState = rcaState;

//Scale stuff
HX711 scale;
#define DOUT  3
#define CLK  2

// Timer to be sure that enough time has elapsed between ADC reading
hw_timer_t *adcTimer = NULL;
int adcPeriod = 6225;    //Time between adc readings. Necessary to let the ADC make its conversion
// int adcPeriod = 1000000;

//Data comming from the cell after resting the offset weight
float offsetted_data = 0;

//Data resulting of appying the calibration_factor to the offsetted_data
float scaled_data = 0;

//The weight used to calibrate the cell
float weight = 0.0;

//The value of the readed force
float force = 0.0;
int forceInt = 0; //send to Chronojump

unsigned long forceTime = 0;

bool adcFlag = false;

// Encoder stuff
#define EncoderAPin 9
#define EncoderBPin 8
#define EncoderZPin 7
bool encoderFlag = false;
bool flagZ= false;
int currentPosition = 0;
int lastPosition = 0;
unsigned long encoderTime = 0;
unsigned int pps = 10;

void setup() {
  Serial.begin(115200);
  Serial.flush();
  scale.begin(DOUT, CLK);


  attachInterrupt(EncoderZPin, changedZ, FALLING);
  attachInterrupt(EncoderAPin, changedA, RISING);   //TODO: implement the possibility of detect every change in both signals. It makes the precission 4 times better
  pinMode(EncoderBPin, INPUT);

  // pinMode(LED_BUILTIN, OUTPUT);

  preferences.begin("forceSensor", false);              //Initate namespace
  scale.set_offset(preferences.getLong("tare", 0));    //Set tare value with stored value
  scale.set_scale(preferences.getFloat("calibration")); //Set calibration value with stored value

  // attachInterrupt(digitalPinToInterrupt(rcaPin), changingRCA, CHANGE);
  initializeBLE();
  adcTimer = timerBegin(1, 80, true);
  timerAlarmWrite(adcTimer, adcPeriod, true);
  timerAlarmEnable(adcTimer);
  timerAttachInterrupt(adcTimer, &readADC, true);
}

void loop() {

  if (capturing)
  {
    /* Triggers not yet implemented
    if (rcaState != lastRcaState) {       //Event generated by the RCA
      Serial.print(triggerTime);
      Serial.print(";");

      if (rcaState) {
        Serial.println("R");
      } else {
        Serial.println("r");
      }
      lastRcaState = rcaState;
    }
    */

    if (testing_b) // only binary, right now just send testingData at each adcFlag
    {
      if (adcFlag)
      {
        Serial.write((byte*)&testingData,12);
        adcFlag = false;
        return;
      }
    }
    
    if (adcFlag) {
      // detachInterrupt(digitalPinToInterrupt(rcaPin));
      //Printing to serial lasts 32 ms
        sample.sensorType = loadCell;
        sample.time = forceTime;
        //sample.data = force;
        forceInt = (int) 100 * force;
        sample.data = forceInt;
      if (transmissionFormat == text) {
        Serial.print(forceTime);
        Serial.print(";");
        //Serial.print(force, 2); //scale.get_units() returns a float
        Serial.print(forceInt);
        Serial.print(";");
        Serial.println(sample.sensorType);
        // attachInterrupt(digitalPinToInterrupt(rcaPin), changingRCA, CHANGE);
        rcaState = digitalRead(rcaPin);
      }
      else { // (transmissionFormat == binary)
        Serial.write((byte*)&sample,12);
        //Serial.write((byte*)&sample.sensorType,4);
        //Serial.write((byte*)&sample.time,4);
        //Serial.write((byte*)&sample.data,4);
        
        // funciona
        //int send1 = 1;
        //Serial.write((byte*)&send1,2);

        // funciona
        //int send7 = 7;
        //Serial.write((byte*)&send7,4);

        // funciona
        //int sendNow = 16909060; //1*256^3 + 2*256^2 + 3*256^1 +4
        //Serial.write((byte*)&sendNow,4);
        //Serial.write((byte*)&testing,12);
      }
      sendToBLE(loadCell);

      adcFlag = false;
    }
    
    if (encoderFlag) {
        sample.sensorType = incEncoder;
        sample.time = encoderTime;
        //sample.data = (float)lastPosition;
        sample.data = lastPosition;
      if (transmissionFormat == text) {
        Serial.print(encoderTime);
        Serial.print(";");
        Serial.print(lastPosition);
        Serial.print(";");
        Serial.println(sample.sensorType);
      }
      else { // (transmissionFormat == binary)
        Serial.write((byte*)&sample,12);
      }
      encoderFlag = false;
      sendToBLE(incEncoder);
    }
       
  }

  //Checking if there's incoming serial data
  if (Serial.available()) {
    processCommand(Serial.readString());
  }

  if (commandFlag) {
    // digitalWrite(LED_BUILTIN, HIGH);
  }
}

void changingRCA() {
  triggerTime = totalTime;
  rcaState = digitalRead(rcaPin);
}

//In old version SerialEvent() was used but the nano every don't support it
void processCommand(String inputString)
{
  String commandString = inputString.substring(0, inputString.lastIndexOf(":"));

  if (commandString == "start_capture") {
    start_capture();
  }
  else if (commandString == "start_capture_binary") {
    transmissionFormat = binary;
    start_capture();
  }
  else if (commandString == "start_capture_text") {
    transmissionFormat = text;
    start_capture();
  }
  else if (commandString == "start_capture_testing") {
    transmissionFormat = binary;
    testing_b = true;
    start_capture();
  }
  else if (commandString == "end_capture") {
    end_capture();
  } else if (commandString == "get_version") {
    get_version();
  } else if (commandString == "get_calibration_factor") {
    get_calibration_factor();
  } else if (commandString == "set_calibration_factor") {
    set_calibration_factor(inputString);
  } else if (commandString == "calibrate") {
    calibrate(inputString);
  } else if (commandString == "get_tare") {
    get_tare();
  } else if (commandString == "set_tare") {
    set_tare(inputString);
  } else if (commandString == "tare") {
    tare();
  } else if (commandString == "set_bps") {
    set_bps(inputString);
  } else if (commandString == "get_transmission_format") {
    get_transmission_format();
  } else {
    Serial.println("Not a valid command");
  }
  inputString = "";
  //  }
}

void start_capture()
{
  Serial.println("Starting capture...");
  totalTime = 0;
  capturing = true;
}

void end_capture()
{
  capturing = false;
  Serial.println("Capture ended:");
}
void get_version()
{
  Serial.println(version);
}

String get_command_argument(String inputString)
{
  return (inputString.substring(inputString.lastIndexOf(":") + 1, inputString.lastIndexOf(";")));
}

void get_transmission_format()
{
  if (transmissionFormat == binary)
  {
    Serial.println("binary");
  } else if (transmissionFormat == text)
  {
    Serial.println("text");
  }
}

void set_bps(String inputString){
  String speedString = get_command_argument(inputString);
  unsigned long speed = speedString.toInt();
  
  Serial.print("setting to: ");
  Serial.print(speed);
  Serial.println(" bps");
  Serial.flush();
  Serial.begin(speed);
  Serial.print("Speed set to: ");
  Serial.print(speed);
  Serial.println(" bps");
}
