#!/bin/sh
cd $(dirname "$0")
mkdir -p "$1bin/angle/"
cp -r "./angle/" "$1bin/angle/"
mkdir -p "$1bin/chronojump-importer/"
cp -r "./chronojump-importer/" "$1bin/chronojump-importer/"
mkdir -p "$1po/"
cp -r "../po/" "$1po/"
mkdir -p "$1share/chronojump/images/"
cp -r "../win32/chronojump_icon.ico" "$1share/chronojump/images/chronojump_icon.ico"
cp -r "../encoder/" "$1share/chronojump/encoder/"
cp -r "../package/macos/deps/" "$1"
mkdir -p "$1share/doc/chronojump/"
cp -r "../manual/" "$1share/doc/chronojump/"
rm -rf "$1bin/chronojump-importer/Makefile.in"
rm -rf "$1bin/chronojump-importer/Makefile.am"
rm -rf "$1bin/chronojump-importer/Makefile"
rm -rf "$1bin/encoder/Makefile.in"
rm -rf "$1bin/encoder/Makefile.am"
rm -rf "$1bin/encoder/Makefile"
rm -rf "$1po/Makefile.in.in"
rm -rf "$1po/Makefile.in"
rm -rf "$1po/Makefile.am"
rm -rf "$1po/Makefile"
rm -rf "$1share/doc/chronojump/Makefile.in"
rm -rf "$1share/doc/chronojump/Makefile.am"
rm -rf "$1share/doc/chronojump/Makefile"