#!/bin/sh
cd $(dirname "$0")
mkdir -p "$1/bin/"
cp -r "./angle/" "$1/bin/angle/"
cp -r "./chronojump-importer/" "$1/bin/chronojump-importer/"
cp -r "../po/" "$1/po/"
mkdir -p "$1/share/chronojump/images/"
cp -r "../win32/chronojump_icon.ico" "$1/share/chronojump/images/chronojump_icon.ico"
cp -r "../encoder/" "$1/share/chronojump/encoder/"
cp -r "../package/linux/deps/bin" "$1/"
cp -r "../package/linux/deps/etc" "$1/"
cp -r "../package/linux/deps/fonts" "$1/"
cp -r "../package/linux/deps/FTD2XX_NET_v1.2.0" "$1/"
cp -r "../package/linux/deps/library" "$1/"
cp -r "../package/linux/deps/modules" "$1/"
mkdir -p "$1/share/doc/chronojump/"
cp -r "../manual/" "$1/share/doc/chronojump/"
rm -rf "$1/bin/chronojump-importer/Makefile.in"
rm -rf "$1/bin/chronojump-importer/Makefile.am"
rm -rf "$1/bin/chronojump-importer/Makefile"
rm -rf "$1/bin/encoder/Makefile.in"
rm -rf "$1/bin/encoder/Makefile.am"
rm -rf "$1/bin/encoder/Makefile"
rm -rf "$1/po/Makefile.in.in"
rm -rf "$1/po/Makefile.in"
rm -rf "$1/po/Makefile.am"
rm -rf "$1/po/Makefile"
rm -rf "$1/share/doc/chronojump/Makefile.in"
rm -rf "$1/share/doc/chronojump/Makefile.am"
rm -rf "$1/share/doc/chronojump/Makefile"