#!/bin/sh
cd $(dirname "$0")
cp -r "../package/linux/deps/bin/" "$1/"
cp -r "../package/linux/deps/lib/" "$1/"
cp -r "../package/linux/deps/share/" "$1/"
#tar -xf ../package/linux/deps/x86_64-linux-gnu.tar.xz -C $1/
cp -r "./angle/" "$1/bin/angle/"
cp -r "./chronojump-importer/" "$1/bin/chronojump-importer/"
cp -r "../encoder/" "$1/bin/encoder/"
cp -r "../po/" "$1/po/"
mkdir -p "$1/share/chronojump/images/"
cp -r "../win32/chronojump_icon.ico" "$1/share/chronojump/images/chronojump_icon.ico"
rm -rf "$1/bin/chronojump-importer/Makefile.in"
rm -rf "$1/bin/chronojump-importer/Makefile.am"
rm -rf "$1/bin/chronojump-importer/Makefile"
rm -rf "$1/bin/encoder/Makefile.in"
rm -rf "$1/bin/encoder/Makefile.am"
rm -rf "$1/bin/encoder/Makefile"
rm -rf "$1/po/Makefile.in.in"
rm -rf "$1/po/Makefile.in"
rm -rf "$1/po/Makefile.am"
rm -rf "$1/po/Makefile"